# Get all products (localhost)
GET http://localhost:5000/products
Content-Type: application/json

###

# Get API Documentation (localhost)
GET http://localhost:5000/api-docs

###

# Get a single product by ID (localhost)
GET http://localhost:5000/products/6708a8eba67c98df7a374963
Content-Type: application/json

###

# Create a new product (localhost)
POST http://localhost:5000/products
Content-Type: application/json

{
  "name": "Laptop",
  "description": "A high-end gaming laptop",
  "quantity": 10,
  "price": 1499.99,
  "category": "Electronics",
  "supplier": "TechStore"
}

###

# Update a product (localhost)
PUT http://localhost:5000/products/6713e0fe128a9bcedb2f6205
Content-Type: application/json

{
  "name": "Updated Laptop",
  "description": "A high-end gaming laptop with RTX 3080",
  "quantity": 5,
  "price": 1999.99,
  "category": "Electronics",
  "supplier": "Updated TechStore"
}

###

# Delete a product (localhost)
DELETE http://localhost:5000/products/6713e0fe128a9bcedb2f6205
Content-Type: application/json

###

# Get all products (published link)
GET https://project2-curg.onrender.com/products
Content-Type: application/json

###

# Get API Documentation (published link)
GET https://project2-curg.onrender.com/api-docs

###

# Get a single product by ID (published link)
GET https://project2-curg.onrender.com/products/66f4c270b530905c84719dec
Content-Type: application/json

###

# Create a new product (published link)
POST https://project2-curg.onrender.com/products
Content-Type: application/json

{
  "name": "Laptop",
  "description": "A high-end gaming laptop",
  "quantity": 10,
  "price": 1499.99,
  "category": "Electronics",
  "supplier": "TechStore"
}

###

# Update a product (published link)
PUT https://project2-curg.onrender.com/products/67016e595e15ed45c841c98b
Content-Type: application/json

{
  "name": "Updated Laptop",
  "description": "A high-end gaming laptop with RTX 3080",
  "quantity": 5,
  "price": 1999.99,
  "category": "Electronics",
  "supplier": "Updated TechStore"
}

###

# Delete a product (published link)
DELETE https://project2-curg.onrender.com/products/67016e595e15ed45c841c98b
Content-Type: application/json